### PR TITLE
Nova setup w/ Saving and user/balance module

### PR DESCRIPTION
**Pull request by VaibhavArora19**
Related to #5 issue

### CODE REVIEW

**Comment by VaibhavArora19** [comment]
POST route for saving is still remaining!

**Review by thelazyindian — COMMENTED** [review]
LGTM! just a small suggestion, let's maintain either snake case or lower camel case in our types, currently its mixed at places. Personally i like lower camel case e.g. `fiatPrice` instead of `fiat_price`, also `apy` instead of `APY`

**Comment by VaibhavArora19** [comment]
> LGTM! just a small suggestion, let's maintain either snake case or lower camel case in our types, currently its mixed at places. Personally i like lower camel case e.g. `fiatPrice` instead of `fiat_price`, also `apy` instead of `APY`

Fixed!

**Review by jakekidd — APPROVED** [review]
lgtm, good work with nest. see 1 comment here about file names

**Review by Yash-Garg — APPROVED** [review]

**Pull request merged**
